Metrics information on COVID-19
Irirwanirira/metrics-webapp pull request #1
Opened 2022-11-30 13:11 UTC by Irirwanirira

## This PR consists of:

- [ ] Chose external API.
- [ ]  Created a home page.
- [ ]  Created a detailed page.
- [ ]  Styled my app.
- [ ] Modified readme file.
- [ ] Created a test for the components and mocked the redux function.
- [ ] Deployed the project.

 ### Thank you for reviewing my project

2022-11-30 16:23 UTC, youmari requested changes
Hi @Irirwanirira , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 16:23 UTC, youmari commented on src/components/Home.js
> +};
- [ ] it would be better if you add a way to filter the data as required in order to complete the requirements 
- Screenshot of the requirements 
<img width="1069" alt="Screenshot 2022-11-30 at 17 13 54" src="https://user-images.githubusercontent.com/61790587/204850755-526c477d-1b54-4636-887e-99243455fb55.png">

2022-11-30 16:23 UTC, youmari commented on src/components/Home.js
> +};
- [x] it would be better to follow the spacing, and layouts as in the given design in order to match 

1. Right now your design is not responsive you shouldn't leave any space between cards as in the Design 
2. should be responsive in all mobile screens 
3. please make sure to use the right font in the Design 
- Screenshot of the requirements 
<img width="562" alt="Screenshot 2022-11-30 at 17 11 48" src="https://user-images.githubusercontent.com/61790587/204852907-5eb52511-053a-4d2e-906a-d4f175c270e2.png">

- Yours 
<img width="587" alt="Screenshot 2022-11-30 at 16 55 58" src="https://user-images.githubusercontent.com/61790587/204851412-5f4ce064-f742-44c4-941e-2b69e576a201.png">
<img width="638" alt="Screenshot 2022-11-30 at 17 07 17" src="https://user-images.githubusercontent.com/61790587/204851456-105f657b-f054-4cc8-aec6-b91dbf775842.png">
- Design 
<img width="205" alt="Screenshot 2022-11-30 at 17 12 55" src="https://user-images.githubusercontent.com/61790587/204851494-99fc34bf-92c4-4ad9-884f-3f685cd11752.png">
- Font 
<img width="807" alt="Screenshot 2022-11-30 at 17 12 25" src="https://user-images.githubusercontent.com/61790587/204851532-6afc77f8-58b1-416b-9809-ba2308e197fe.png">

2022-11-30 16:23 UTC, youmari commented on src/tests/Home.test.js
> +  });
- [ ] as required you should also add tests for redux pure functions in order to complete the requirements 
- Screenshot of the requirements
<img width="1069" alt="Screenshot 2022-11-30 at 17 13 54" src="https://user-images.githubusercontent.com/61790587/204852583-98b56912-facf-4f6f-9ad1-767095209fda.png">

2022-12-01 08:19 UTC, Irirwanirira commented on src/components/Home.js
> +};
Thank you for you review

2022-12-01 08:19 UTC, Irirwanirira commented on src/components/Home.js
> +};
Done, Thank you.

2022-12-01 11:06 UTC, AmaduKamara approved these changes
# Status: Approved 🟢🟢🟢 

Hi @Irirwanirira,

Good job on making the changes asked by the previous reviewer,

Your project is complete!  

## Highlights:
✅ Used Gitflow correctly 👍 
✅ Linter checks passed 👍 
✅ Good commit messages 👍 
✅ Good descriptive PR 👍 
✅ App is hosted properly and works fine as expected 👍 
✅ Good video presentation 👍 

There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-01 14:18 UTC, merged